//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Makale = new HashSet<Makale>();
        }
    
        public int Kid { get; set; }
        [Required]
        [Display(Name ="kadi",ResourceType =typeof(Resources.Dil))]
        public string Kadi { get; set; }
        [Display(Name = "sifre", ResourceType = typeof(Resources.Dil))]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
        [Required]
        [Display(Name = "adsoyad", ResourceType = typeof(Resources.Dil))]
        public string AdSoyad { get; set; }
        [Required]
        public string Email { get; set; }
        [Display(Name = "uyeliktarihi", ResourceType = typeof(Resources.Dil))]
        public Nullable<System.DateTime> UyelikTarihi { get; set; }
        [Display(Name = "fotograf", ResourceType = typeof(Resources.Dil))]
        public string Foto { get; set; }

        [Display(Name = "yetki", ResourceType = typeof(Resources.Dil))]
        public string Yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makale> Makale { get; set; }
    }
}
