//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Makale
    {
        public int Mid { get; set; }
        [Required]

        [Display(Name = "baslik", ResourceType = typeof(Resources.Dil))]
        public string Baslik { get; set; }

        [Required]
        [Display(Name = "kisaicerik", ResourceType = typeof(Resources.Dil))]
        public string KisaIcerik { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "icerik", ResourceType = typeof(Resources.Dil))]
        public string Icerik { get; set; }

        [Display(Name = "fotograf", ResourceType = typeof(Resources.Dil))]
        public string Foto { get; set; }

        [Display(Name = "eklenmetarihi", ResourceType = typeof(Resources.Dil))]
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }

        [Display(Name = "guncellemetarihi", ResourceType = typeof(Resources.Dil))]
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public int KatId { get; set; }
        public int Kid { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
