//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dil() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Resources.Dil", typeof(Dil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ad Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adsoyad {
            get {
                return ResourceManager.GetString("adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Sayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ana Sayfaya Dön benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string anasayfayadon {
            get {
                return ResourceManager.GetString("anasayfayadon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ara {
            get {
                return ResourceManager.GetString("ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ayarlar {
            get {
                return ResourceManager.GetString("ayarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı Güncelleme İşlemi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string basariliguncelleme {
            get {
                return ResourceManager.GetString("basariliguncelleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Başarıyla Gönderildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string basariliiletisim {
            get {
                return ResourceManager.GetString("basariliiletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bir Hata Oluştu! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string birhataolustu {
            get {
                return ResourceManager.GetString("birhataolustu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış yap butonuna tıklayarak sistemden çıkabilirsin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cikismetin {
            get {
                return ResourceManager.GetString("cikismetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cikisyap {
            get {
                return ResourceManager.GetString("cikisyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matriste Bir Aksaklık Bulmuş Gibisin.... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string d04mesaj {
            get {
                return ResourceManager.GetString("d04mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Değiştirilecek Yeni Şifreyi Girin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string degistirilecekyenisifre {
            get {
                return ResourceManager.GetString("degistirilecekyenisifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detaylar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string detaylar {
            get {
                return ResourceManager.GetString("detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Devamını Oku benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string devaminioku {
            get {
                return ResourceManager.GetString("devaminioku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dili Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dildegistir {
            get {
                return ResourceManager.GetString("dildegistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string duzenle {
            get {
                return ResourceManager.GetString("duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eklenme Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eklenmetarihi {
            get {
                return ResourceManager.GetString("eklenmetarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emin misin? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string eminmisin {
            get {
                return ResourceManager.GetString("eminmisin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen Formu Kontrol Edin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string formukontrolet {
            get {
                return ResourceManager.GetString("formukontrolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fotoğraf benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fotograf {
            get {
                return ResourceManager.GetString("fotograf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string gecersizkul {
            get {
                return ResourceManager.GetString("gecersizkul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string girisyap {
            get {
                return ResourceManager.GetString("girisyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelleme Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string guncellemetarihi {
            get {
                return ResourceManager.GetString("guncellemetarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hata {
            get {
                return ResourceManager.GetString("hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoş Geldiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hosgeldiniz {
            get {
                return ResourceManager.GetString("hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İçerik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string icerik {
            get {
                return ResourceManager.GetString("icerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletişim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İptal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string iptal {
            get {
                return ResourceManager.GetString("iptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kadi {
            get {
                return ResourceManager.GetString("kadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kategori {
            get {
                return ResourceManager.GetString("kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kategoriadi {
            get {
                return ResourceManager.GetString("kategoriadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategoriler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kategoriler {
            get {
                return ResourceManager.GetString("kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori Başarıyla Silindi! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string katsilindi {
            get {
                return ResourceManager.GetString("katsilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kaydol {
            get {
                return ResourceManager.GetString("kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kısa İçerik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kisaicerik {
            get {
                return ResourceManager.GetString("kisaicerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string konu {
            get {
                return ResourceManager.GetString("konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı veya şifre hatalı! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kuladisifrehatali {
            get {
                return ResourceManager.GetString("kuladisifrehatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kullanici {
            get {
                return ResourceManager.GetString("kullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcılar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kullanicilar {
            get {
                return ResourceManager.GetString("kullanicilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Başarıyla Silindi! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kulsilindi {
            get {
                return ResourceManager.GetString("kulsilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Listeye Geri Dön benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string listeyedon {
            get {
                return ResourceManager.GetString("listeyedon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makale benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string makale {
            get {
                return ResourceManager.GetString("makale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makaleler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string makaleler {
            get {
                return ResourceManager.GetString("makaleler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makale Başarıyla Silindi! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string maksilindi {
            get {
                return ResourceManager.GetString("maksilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesaj benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mesaj {
            get {
                return ResourceManager.GetString("mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string profil {
            get {
                return ResourceManager.GetString("profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sayfa Bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sayfabulunamadi {
            get {
                return ResourceManager.GetString("sayfabulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen Bir Şifre Girin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sifregir {
            get {
                return ResourceManager.GetString("sifregir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifremi Unuttum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sifremiunuttum {
            get {
                return ResourceManager.GetString("sifremiunuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silindi! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string silindi {
            get {
                return ResourceManager.GetString("silindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu kaydın silinmesini istiyor musunuz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string silinecekmetin {
            get {
                return ResourceManager.GetString("silinecekmetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Siteyi Görüntüle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string siteyigoruntule {
            get {
                return ResourceManager.GetString("siteyigoruntule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Paylaşılan İçerikler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sonpaylasilan {
            get {
                return ResourceManager.GetString("sonpaylasilan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon Numarası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üyelik Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string uyeliktarihi {
            get {
                return ResourceManager.GetString("uyeliktarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yeniolustur {
            get {
                return ResourceManager.GetString("yeniolustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetki benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yetki {
            get {
                return ResourceManager.GetString("yetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönetim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yonetim {
            get {
                return ResourceManager.GetString("yonetim", resourceCulture);
            }
        }
    }
}
